# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Royce
subtitle: ''
description: '小白 | OIer | 科技生活 | 高中生'
keywords: Royce
author: Royce
language: 
timezone: 'Asia/Shanghai'

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://royce2003.top
root: /
# permalink: :year/:month/:day/:title/
permalink: posts/:abbrlink.html
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks
  abbrlink:
    alg: crc32   #算法： crc16(default) and crc32
    rep: hex     #进制： dec(default) and hex

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: false
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false


baidu_url_submit:
  count: 200
  host: royce2003.top
  token: baiduToken
  path: baidu_urls.txt

# 外部链接优化
nofollow:
  enable: true
  field: site
  exclude:
    - 'royce2003.top'
    - 'www.royce2003.top'
    - 'music.royce2003.top'
    - 'neworld2002.github.io'
    - 'newsheep2003.github.io'
    - 'huishao.top'
    - 'blog.atuo.store'
    - 'wtrwx.top'
    - 'linhk1606.github.io'
    - 'leflacon.top'
    - 'www.antmoe.com'
    - 'kksan.top'
    - 'eatrice.top'
    - 'blog.wubuster.com'
    - 'www.geek-space.cn'
    - 'mocehu.top'
    - 'codgi.xin'
    - 'apde.xyz'
    - 'idkzr.com'
    - 'yyuzh.xyz'
    - 'ixfish.cn'
    - 'yiki.tech'
    - 'tutouyuan.top'
    - 'pistol.city'
    - 'skyhouse.xyz'
    - 'www.aahy.xyz'
    - 'www.yunyoujun.cn'
    - 'transion.cc'
    - 'xaoxuu.com'
    - 'www.yuhangwei.com'
    - 'bestzuo.cn'
    - 'bibiqo.cn'
    - 'blog.yinuxy.com'
    - 'xiamuyourenzhang.cn'
    - 'tding.top'
    - '713.moe'
    - 'www.julydate.com'
    - 'blog.say521.cn'
    - 'barriery.cn'
    - 'keithqwq.com'
    - 'i.vince.pub'
    - 'www.52efi.cn'
    - 'blog.juanertu.com'
    - 'dmx.pub'
    - 'www.hcode.top'
    - 'neatman.club'
    - 'blog.6yfz.cn'
    - 'bryce-huang.club'
    - 'fanfan.im'
    - 'chungzh.cn'

# Security
encrypt: # hexo-blog-encrypt
  abstract: 有东西被加密啦，输入密码才能看哦
  message: 猜猜密码是什么
  tags:
  - {name: tagName, password: password} # 标签加密方法
  template: <div id="hexo-blog-encrypt" data-wpm="{{hbeWrongPassMessage}}" data-whm="{{hbeWrongHashMessage}}"><div class="hbe-input-container"><input type="password" id="hbePass" placeholder="{{hbeMessage}}" /><label>{{hbeMessage}}</label><div class="bottom-line"></div></div><script id="hbeData" type="hbeData" data-hmacdigest="{{hbeHmacDigest}}">{{hbeEncryptedData}}</script></div>
  wrong_pass_message: 这密码感觉不太对, 再猜猜看
  wrong_hash_message: 抱歉, 这个文章不能被校验, 不过您还是能看看解密后的内容

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: MMM DD YYYY
time_format: HH:mm:ss
## Use post's date for updated date unless set in front-matter
use_date_for_updated: false

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

all_minifier: true
js_concator:
  enable: false
  bundle_path: '/js/bundle.js'
  front: false
  silent: false
html_minifier:
  enable: true
  ignore_error: false
  silent: false
  exclude:
css_minifier:
  enable: true
  silent: false
  exclude: 
    - '*.min.css'
js_minifier:
  enable: true
  mangle: true
  silent: false
  output:
  compress:
  exclude: 
    - '*.min.js'

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: fluid

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  - type: cos-cdn 
    cloud: tencent 
    bucket: bucket
    region: region
    secretId: SecretId
    secretKey: SecretKey