#---------------------------
# Hexo Fluid
# Author: Fluid-dev organization
# Github: https://github.com/fluid-dev/hexo-theme-fluid
#
# Docs：https://hexo.fluid-dev.com/docs/guide/
#---------------------------


#---------------------------
# 全局
# Site
#---------------------------
favicon: /img/favicon.ico # 网站标签页的 icon

apple_touch_icon: /img/favicon.ico # 用于苹果设备的 icon

title_join_string: ' - '  # 浏览器标签页中的标题分隔符，效果： 文章名 ~ 站点名
force_https: true  # 强制所有链接升级为 HTTPS（适用于图片等资源出现 HTTP 混入报错）

highlight: # 代码高亮
  enable: true
  style: 'Atom One Dark'  # 以在 custom.styl 内置，高亮样式见：https://highlightjs.org/static/demo/
  bg_color: true  # 是否根据 style 改变代码背景色，如果 style 是白色背景最好关闭此项
  copy_btn: true  # 是否开启复制代码的按钮

fun_features: # 一些好玩的功能
  typing: # 为 subtitle 添加打字机效果
    enable: true
    typeSpeed: 70  # 打印速度，数字越大越慢
    cursorChar: "_" # 游标字符
    loop: false # 是否循环播放效果
  anchorjs: # 为文章内容中的标题添加锚图标
    enable: false
    element: h1,h2,h3,h4,h5,h6
    placement: right # icon放置的位置： left | right
    visible: hover # 默认悬浮显示，可选：hover（鼠标在元素上悬浮时显示） | always（一直显示） | touch（移动端触摸显示）
    icon: "❡" # 可选：§ | # | ❡ 等，留空则为默认效果
  mouse_click:  # 鼠标点击动效
    enable: false
    style: values # 目前设置两个值：values（价值观词汇） | love（爱心）

color:  # 主题颜色配置，不一定能每一处都生效，可能会被局部样式覆盖，这种情况建议用自定义 css 解决。配色可以在这获得启发： https://www.webdesignrankings.com/resources/lolcolors/
  body_bg_color: "#eee"             # body 背景色
  navbar_bg_color: "#2f4154"        # 顶部菜单背景色
  navbar_text_color: "white"        # 顶部菜单字体色
  text_color: "#3c4858"             # 全局字体色
  sec_text_color: "#718096"         # 全局次级字体色（摘要、简介等位置）
  post_text_color: "#333"           # 文章正文字体色
  post_heading_color: "#1a202c"     # 文章标题标签字体色（h1 h2 h3...）
  link_color: "#3c4858"             # 超链接字体色
  link_hover_color: "#1abc9c"       # 超链接悬浮时字体色
  link_hover_bg_color: "#ebedef"    # 超链接悬浮背景色
  board_color: "#fff"               # 主面板背景色

font:  # 主题字体配置
  font_size: 1.1rem # 全局字号
  font_family: "'Fira Code', 'Noto Serif SC', serif " # 全局字体
  code_font_size: 100% # 代码的字号

custom_js: # 指定自定义 js 文件路径，路径是相对 source 目录，如 /js/custom.js 对应存放目录 source/js/custom.js，支持列表
custom_css: /css/custom.css # 指定自定义 css 文件路径，路径是相对 source 目录，如 /css/custom.css 同上，支持列表
custom_html: ''  # 自定义底部 HTML 内容（位于 footer 上方），也可用于外部引入 js css 这些操作，注意不要和 post.custom 配置冲突

web_analytics:  # 网页访问统计
  enable: true
  baidu: 3b1c52021da1d2ea4a18cb97b7313fd0 # 百度统计的Key，参见 https://tongji.baidu.com/sc-web/10000033910/home/site/getjs?siteId=13751376 代码获取中 hm.js? 后边的字符串
  google: # Google统计的Tracking ID，参见 https://analytics.google.com/analytics/web/
  tencent:  # 腾讯统计的H5 App id，参见 https://mta.qq.com/h5/manage/ctr_app_manage (开启高级功能才有cid)
    sid:
    cid:
  tajs: # 腾讯统计早期版站点统计sID，参见 https://ta.qq.com/#/site/list
  woyaola:  # 51.la站点统计ID，参见 https://www.51.la/user/site/index
  cnzz:  # 友盟/cnzz站点统计web_id，参见 https://web.umeng.com/main.php?c=site&a=show

lazyload: # 对页面中的图片进行懒加载处理，可见范围外的图片不会加载
  enable: true
  onlypost: true  # 仅在文章页使用懒加载，开启后如果自定义页面需要使用，可以在 Front-matter 里指定 `lazyload: true`
  image: https://cdn.jsdelivr.net/gh/Royce2019/BlogSource/loading.webp

daovoice:  # 在线客服 Daovoice 参考：http://dashboard.daovoice.io
  enable: false # 是否开启在线客服聊天
  appid: ''  # 应用ID设置

aplayer:  # 音乐播放器，注意不能与 hexo-tag-aplayer 插件共用
  enable: false
  autoplay: true  # 音频自动播放
  loop: 'all'  # 音频循环播放, 可选值: 'all', 'one', 'none'
  order: 'random'  # 播放顺序，可选值: 'list', 'random'
  theme: '#b7daff'  # 主题色
  songs:  # 歌曲列表，必须传入下列各参数，其中 url 与 cover 在本地需存于 source 目录，更多参数见文档：https://aplayer.js.org/#/zh-Hans/?id=%E5%8F%82%E6%95%B0
    - { name: 'となりのトトロ', artist: '伊藤サチコ', url: 'https://cdn.jsdelivr.net/gh/Royce2019/img/01.mp3', cover: 'https://cdn.jsdelivr.net/gh/Royce2019/img/img/109951163028865726.jpg' }
    - { name: 'それがあなたの幸せとしても (カバー)', artist: 'rairu', url: 'https://cdn.jsdelivr.net/gh/Royce2019/img/02.mp3', cover: 'https://cdn.jsdelivr.net/gh/Royce2019/img/img/109951163597938340.jpg' }

version:  # 版本相关
  check: false  # 每次生成检测是否为最新版本


#---------------------------
# 页头
# Header
#---------------------------
navbar:
  blog_title: Royce's world # 导航栏左侧的标题，为空则按 hexo config.title 显示
  menu:  # 可自行增减，key 用来关联 languages/*.yml，如不存在关联则显示 key 本身的值，增加 name 可以强制显示指定名称
    # - { key: 'home', link: 'https://www.royce2003.top', icon: 'iconfont icon-home-fill' }
    # - { key: 'archive', link: '/archives/', icon: 'iconfont icon-archive-fill' }
    - { key: 'tag', link: '/tags/', icon: 'iconfont icon-tags-fill' }
    - { key: 'gallery', link: '/gallery/', icon: 'iconfont icon-xiangce1' }
    - { key: 'messageboard', link: '/messageboard/', icon: 'iconfont icon-liuyan' }
    - { key: 'links', link: '/links/', icon: 'iconfont icon-link-fill' }
    - { key: 'about', link: '/about/', icon: 'iconfont icon-user-fill' }
    - { key: 'tools', link: '/tools/', icon: 'iconfont icon-laboratory' }

search: # 搜索栏
  enable: false
  path: /local-search.xml # 文件引用地址，默认是下方生成位置，也可以将生成后的 local-search.xml 上传到其它位置引用，如：https://www.example.com/local-search.xml
  generate_path: /local-search.xml # 文件生成位置，必须为相对位置
  field: post
  content: true

scroll_down_arrow:  # 向下滚动的箭头
  enable: true
  banner_height_limit: 90  # 头图高度不小于指定比例，才显示箭头
  scroll_after_turning_page: true  # 翻页后自动滚动

banner_parallax: true # 头图滚动视差


#---------------------------
# 页脚
# Footer
#---------------------------
footer:
  statistics:  # 统计网站 PV、UV，使用的是不蒜子，显示在页脚
    enable: false
    pv_format: "{}&nbsp;次回眸"  # 显示的文本，{}是数字的占位符（必须包含)，下同
    uv_format: "遇见了&nbsp;{}&nbsp;个小伙伴"

  beian:  # The footer of China's website policy, other areas keep disable
    enable: true
    icp_text: 闽ICP备20005437号-1 # ICP证号
    police_text:  # 公安备案号，不填则只显示ICP
    police_code:  # 公安备案的编号，用于URL跳转查询
    police_icon: /img/police_beian.png # 公安备案的图片. 为空时不显示备案图片

scroll_top_arrow:  # 向顶部滚动的箭头
  enable: true


#---------------------------
# 首页
# Index Page
#---------------------------
index:
  banner_img: https://rmt.dogedoge.com/fetch/royce/storage/bg/1.jpg?fmt=webp  # 首页 Banner 头图，以下相同
  banner_img_height: 100  # 头图高度，屏幕百分比，available: 0 - 100
  banner_mask_alpha: 0.3  # 头图黑色蒙版的透明度，available: 0 - 1.0， 0 是完全透明（无蒙版），1 是完全不透明
  post_default_img:   # 随机默认文章封面图，当没有指定 index_img 时会使用该文件夹中的图片，若都为空则不显示任何图片
    url: https://cos.royce2003.top/index_img # 默认的文章封面图文件夹
    number: 3 # 文件夹中图片数量，图片命名从0开始 0.jpg 1.jpg 2.jpg
    format: webp # 图片格式，保证文件夹中图片格式一致
  slogan:  # 首页副标题的独立设置
    enable: true  # 为 false 则不显示任何内容
    text: 今日任务：早起 (0/1) # 为空则按 hexo config.subtitle 显示
  auto_excerpt:
    enable: true
  post_url_target: _self  # available: _blank | _self
  post_meta: # 是否显示文章信息（时间、分类、标签）
    date: true
    category: false
    tag: true


# 通过 hexo new page 命令创建的页面
# Custom Page
page:
  banner_img: https://rmt.dogedoge.com/fetch/royce/storage/bg/1.jpg?fmt=webp
  banner_img_height: 80  # available: 0 - 100
  banner_mask_alpha: 0.3  # available: 0 - 1.0

#---------------------------
# 文章页
# Post Page
#---------------------------
post:  # 部分配置同时控制自定义页面，注意备注
  banner_img: https://rmt.dogedoge.com/fetch/royce/storage/bg/1.jpg?fmt=webp
  banner_img_height: 80  # available: 0 - 100
  banner_mask_alpha: 0.3  # available: 0 - 1.0
  meta:  # 文章标题下方的信息
    date:  # 文章日期
      enable: true
      format: "ddd MMM DD YYYY"  # 格式参照 ISO-8601 日期格式化
    wordcount:  # 字数统计
      enable: true
      format: "{}"  # 显示的文本，{}是数字的占位符（必须包含)，下同
    min2read:  # 阅读时间
      enable: false
      format: "{} 分钟"
      words: 100  # 每分钟阅读多少字，如果是技术文章，建议降低
    views:  # 阅读次数，统计基于不蒜子
      enable: false
      format: "{} 次"
  updated:  # 在文章开头显示文章更新时间，该时间默认是 md 文件更新时间，可通过 front-matter 中 `updated` 手动指定（和 date 一样格式）
    enable: false
    content: 本文最后更新于：  # 描述文字
    relative: true  # 是否使用相对时间表示，比如："3 天前"
  toc:  # 文章右侧目录
    enable: true
    headingSelector: h1,h2,h3,h4,h5,h6
    collapseDepth: 0  # 层级的折叠深度，0 是全部折叠，6 是全部不折叠
  copyright:  # 版权声明
    enable: true
    content: '本博客文章除特别声明外，均采用 <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh">CC BY-NC-SA 4.0 协议</a>。转载请注明出处！'
  prev_next:  # 文章底部上一篇下一篇功能
    enable: false
  custom:  # 文章底部自定义内容
    enable: false
    content: '<img src="https://octodex.github.com/images/jetpacktocat.png" class="rounded mx-auto d-block mt-5" style="width:150px; height:150px;">' # 自定义区域，支持 HTML，可自行插入赞赏码、公众号二维码等内容
  image_zoom:  # 文章图片可点击放大
    enable: true  # 开启后文章默认可用，自定义页面如需使用，需在 Front-matter 中指定 `image_zoom: true`，并且图片使用该格式插入：<img src="..." zoom />
  math:  # 数学公式，开启之前需要更换 Markdown 渲染器，否则复杂公式会有兼容问题，具体请见：https://hexo.fluid-dev.com/docs/guide/##latex-数学公式
    enable: true  # 开启后文章默认可用，自定义页面如需使用，需在 Front-matter 中指定 `math: true`
    specific: true  # 开启后，只有在文章 Front-matter 里指定 `math: true` 才会在文章页启动公式转换，以便在页面不包含公式时提高加载速度
    engine: katex  # 公式引擎  available: mathjax | katex
  mermaid:  # 流程图，基于 mermaid-js，文档：http://mermaid-js.github.io/mermaid/
    enable: false  # 开启后文章默认可用，自定义页面如需使用，需在 Front-matter 中指定 `mermaid: true`
    specific: false  # 开启后，只有在文章 Front-matter 里指定 `mermaid: true` 才会在文章页启动公式转换，以便在页面不包含公式时提高加载速度
    options: { theme: 'default' }  # 接口选项，具体可见：http://mermaid-js.github.io/mermaid/#/mermaidAPI
  comments:  # 评论
    enable: true  # 开启评论
    type: valine  # 指定使用的评论模块  available: disqus | valine | gitalk | utterances | changyan | livere  推荐 utterances


#---------------------------
# 评论
# Comments
#---------------------------

# 开启评论需要先在上方 post.comments.enable: true

# utterances
# You can install utterances with https://utteranc.es/ and generate your configuration
utterances:
  repo:
  issue_term:
  label: utterances
  theme: github-light
  crossorigin: anonymous

# Disqus
# 国内用户不要用，已被墙
disqus:
  shortname: # your shortname

# Gitalk
# You can get yout ClientID and ClientSecret from https://github.com/settings/applications/new
# More info available at https://github.com/gitalk/gitalk#options
gitalk:
  clientID:                     # GitHub Application Client ID
  clientSecret:                 # GitHub Application Client Secret
  repo:                         # The repo to store comments
  owner:                        # GitHub repository owner. Can be personal user or organization.
  admin:                        # GitHub repo owner and collaborators, only these guys can initialize github issues, should be like "['admin']" or "['admin1','admin2']"
  id: location.pathname         # The unique id of the page. Length must less than 50.
  language: zh-CN               # Localization language key, en, zh-CN and zh-TW are currently available.
  labels: "['Gitalk']"          # GitHub issue labels.
  perPage: 15                   # Pagination size, with maximum 100.
  pagerDirection: last          # Comment sorting direction, available values are last and first.
  distractionFreeMode: false    # Facebook-like distraction free mode.
  createIssueManually: true     # By default, Gitalk will create a corresponding github issue for your every single page automatically when the logined user is belong to the admin users. You can create it manually by setting this option to true.

# Valine
# You can get your appid and appkey from https://leancloud.cn
# More info available at https://valine.js.org
valine:
  appid: KIkO2HJm1qz9uykOuuU41i8F-9Nh9j0Va  # your leancloud application appid
  appkey: oJgS2mVg227GJIkndK0bFGtF  # your leancloud application appkey
  placeholder: 说点什么... # comment box placeholder=
  admin_email: 1098870059@qq.com

# 畅言
# http://changyan.kuaizhan.com/
changyan:
  appid: ''
  appkey: ''

# Livere 来必力
# You can get your uid from https://www.livere.com/my_Livere
livere:
  uid: ''


#---------------------------
# 归档页
# Archive Page
#---------------------------
archive:
  banner_img: https://rmt.dogedoge.com/fetch/royce/storage/bg/1.jpg?fmt=webp
  banner_img_height: 80  # available: 0 - 100
  banner_mask_alpha: 0.3  # available: 0 - 1.0
  subtitle: 记下即将逝去的青春，留下即将过去的幸福 # 打字机内容


#---------------------------
# 分类归档页
# Categories Page
#---------------------------
category:
  banner_img: https://rmt.dogedoge.com/fetch/royce/storage/bg/1.jpg?fmt=webp
  banner_img_height: 80  # available: 0 - 100
  banner_mask_alpha: 0.3  # available: 0 - 1.0
  subtitle:  # 打字机内容


#---------------------------
# 标签归档页
# Tags Page
#---------------------------
tag:
  banner_img: https://rmt.dogedoge.com/fetch/royce/storage/bg/1.jpg?fmt=webp
  banner_img_height: 80  # available: 0 - 100
  banner_mask_alpha: 0.3  # available: 0 - 1.0
  subtitle: 今天也是开心的一天 # 打字机内容
  tagcloud: # 标签云
    min_font: 15
    max_font: 30
    unit: px  # 字号单位
    start_color: "#BBBBEE"
    end_color: "#337ab7"


#---------------------------
# 留言板页
# Messageboard Page
#---------------------------
messageboard:
  banner_img: https://rmt.dogedoge.com/fetch/royce/storage/bg/1.jpg?fmt=webp
  banner_img_height: 80  # available: 0 - 100
  banner_mask_alpha: 0.3  # available: 0 - 1.0
  subtitle: 留下你的脚印 # 打字机内容


#---------------------------
# 关于页
# About Page
#---------------------------
about:  # 关于页需要手动创建，具体请见：https://hexo.fluid-dev.com/docs/guide/#关于页
  banner_img: https://rmt.dogedoge.com/fetch/royce/storage/bg/1.jpg?fmt=webp
  banner_img_height: 80  # available: 0 - 100
  banner_mask_alpha: 0.3  # available: 0 - 1.0
  subtitle: '今后无论发生什么事也好<br>这个左手上的⋯⋯都是同伴的记号' # 打字机内容
  avatar: https://cdn.jsdelivr.net/gh/Royce2019/BlogSource/about/Royce.webp # 头像
  name: Royce
  introduce: '<span id="gradient">OI/科技/生活</span>' # 支持 HTML
  icons: # 更多图标可从 https://github.com/fluid-dev/static/blob/master/hexo-theme-fluid/iconfont.png 查找，class 代表图标的 css class
    - { class: 'icon-github_alt', link: 'https://github.com/royce2019' }
    - { class: 'icon-coolapk', qrcode: 'https://cdn.jsdelivr.net/gh/Royce2019/BlogSource/about/coolapk.webp' }
    - { class: 'icon-telegram', link: 'https://t.me/joinchat/PXmDqxgFJOmpx8cADkkc8g' }
    - { class: 'icon-qq', qrcode: 'https://cdn.jsdelivr.net/gh/Royce2019/BlogSource/about/QQ.webp' }
    - { class: 'icon-mail', link: 'mailto:1098870059@qq.com' }


#---------------------------
# 404页
# 404 Page
#---------------------------
page404:
  banner_img: https://rmt.dogedoge.com/fetch/royce/storage/bg/1.jpg?fmt=webp
  banner_img_height: 100  # available: 0 - 100
  banner_mask_alpha: 0.3  # available: 0 - 1.0
  subtitle: 喂，幺幺零吗？这里的页面找不到了 # 打字机内容


#---------------------------
# 友链页
# Links Page
#---------------------------
links:
  banner_img: https://rmt.dogedoge.com/fetch/royce/storage/bg/1.jpg?fmt=webp
  banner_img_height: 80  # available: 0 - 100
  banner_mask_alpha: 0.3  # available: 0 - 1.0
  subtitle: 我们的船上没有手下，只有伙伴 # 打字机内容
  defaultlinks:
    - { title: 'Neworld2002', intro: '蓝鸟', link: 'neworld2002.github.io' }
    - { title: 'Newsheep', intro: '憨憨', link: 'newsheep2003.github.io' }
  friendslinks:
    - { title: 'Atuo', intro: '网络安全', link: 'blog.atuo.store' }
    - { title: '维他入我心', intro: '科技/生活日常～', link: 'wtrwx.top' }
    - { title: 'Linhk1606', intro: '...', link: 'linhk1606.github.io' }
    - { title: 'LeFlacon', intro: 'Let’s think!', link: 'leflacon.top' }
    - { title: '小康博客', intro: '一个收藏回忆与分享技术的地方', link: 'www.antmoe.com' }
    - { title: '小K同學', intro: '技术，日语，云旅游', link: 'kksan.top' }
    - { title: '吃白饭的休伯利安号', intro: '卑微的考研狗', link: 'eatrice.top' }
    - { title: 'IamWu555', intro: 'A man with superb shot', link: 'blog.wubuster.com' }
    - { title: '极客空间', intro: '一个准备高考的高三狗', link: 'www.geek-space.cn' }
    - { title: 'MOCEHU',  intro: '一个没有技术贴的技术博客', link: 'mocehu.top' }
    - { title: 'Codgi', intro: 'Do what you love', link: 'codgi.xin' }
    - { title: 'JimmyQin', intro: '挨拍的儿', link: 'www.apde.workers.dev' }
    - { title: '惴与绕', intro: '一条咸鱼的日常', link: 'idkzr.com' }
    - { title: 'yuzh', intro: '永不停歇--Never Settle', link: 'yyuzh.xyz' }
    - { title: 'Bert', intro: '面朝大海，春暖花开', link: 'ixfish.cn' }
    - { title: 'Guan FuQing', intro: 'Error:No object found!', link: 'yiki.tech' }
    - { title: '辉少菌', intro: '一个爱搞技术的高一党', link: 'huishao.top' }
    - { title: 'TanHua', intro: 'IoT在校生', link: 'tutouyuan.top' }
    - { title: '破旧的手枪', intro: '只争朝夕 不负韶华', link: 'pistol.city' }
    - { title: '星下小屋', intro: '学习记录笔记本', link: 'skyhouse.xyz' }
    - { title: 'MinePHP', intro: 'MinePHP Blog', link: 'www.aahy.xyz' }
    - { title: '云游君', intro: 'All at sea.', link: 'www.yunyoujun.cn' }
    - { title: '以成杂谈', intro: '以成，却非已成', link: 'transion.cc' }
    - { title: 'xaoxuu', intro: 'iOS', link: 'xaoxuu.com' }
    - { title: 'YU到边', intro: '前端技术交流', link: 'www.yuhangwei.com' }
    - { title: 'Sanarous', intro: '码农人生', link: 'bestzuo.cn' }
    - { title: 'Burgess', intro: '日常', link: 'bibiqo.cn' }
    - { title: 'YINUXY', intro: '理想的生活就是生活的理想', link: 'blog.yinuxy.com' }
    - { title: '夏目友人帐', intro: '夏目友人帐', link: 'xiamuyourenzhang.cn' }
    - { title: '小丁', intro: '世间所有的相遇，都是久别重逢', link: 'tding.top' }
    - { title: '小太', intro: '一个热爱ACG的技术宅', link: '713.moe' }
    - { title: '七夏浅笑', intro: '七月之约，夏末浅笑', link: 'www.julydate.com' }
    - { title: 'Mystery', intro: '心有猛虎，细嗅蔷薇', link: 'blog.say521.cn' }
    - { title: 'barriery', intro: 'A student, programmer and explorer.', link: 'barriery.cn' }
    - { title: 'keith', intro: '一个热爱网络的学生', link: 'keithqwq.com' }
    - { title: 'Vince', intro: '努力学习技术的Vince', link: 'i.vince.pub' }
    - { title: '飞雨晴忘乡', intro: '享建站之香，解发少之苦', link: 'www.52efi.cn' }
    - { title: 'ConstOwn', intro: '能和你一起成长，我荣幸之至', link: 'blog.juanertu.com' }
    - { title: 'DmxZ', intro: '欢迎来到 DmxZ 的自留地！', link: 'dmx.pub' }
    - { title: 'Hcode', intro: '记录编程技术，实现在线小功能', link: 'www.hcode.top' }
    - { title: 'Neat', intro: '六六的在线记事本', link: 'neatman.club' }
    - { title: 'LiuYun', intro: '一位信息网络爱好者的博客', link: 'blog.6yfz.cn' }
    - { title: 'Bryce', intro: '啥都想学的程序员', link: 'bryce-huang.club' }
    - { title: '饭庄', intro: '饭庄', link: 'fanfan.im'}
    - { title: 'ChungZH', intro: 'Young, Simple, Naive' ,link: 'chungzh.cn'}


#---------------------------
# 工具页
# Tools Page
#---------------------------
tools:
  banner_img: https://rmt.dogedoge.com/fetch/royce/storage/bg/1.jpg?fmt=webp
  banner_img_height: 80  # available: 0 - 100
  banner_mask_alpha: 0.3  # available: 0 - 1.0
  subtitle: 小玩意儿 # 打字机内容
  items:
    - { title: 'Home', intro: '主页', link: 'https://www.royce2003.top', icon: 'iconfont icon-home-fill' }
    - { title: 'DogeDoge 多吉搜索', intro: '非常好用的搜索引擎，强烈推荐', link: 'https://www.dogedoge.com/' }
    - { title: '疫情图', intro: '国际国内实时疫情图', link: '/tools/2019-nCoV/' }
    - { title: '评论管理', intro: 'Valin 后台评论管理', link: 'https://serve.royce2003.top' }
    - { title: '2048', intro: '2048小游戏', link: '/tools/2048/' }
    - { title: 'Music Player', intro: '简约好看的在线音乐播放器', link: 'http://music.royce2003.top/' }
    - { title: 'WebP 转换', intro: '又拍转 WebP + 智能压缩 Demo', link: 'https://www.upyun.com/webp' }
    - { title: 'Fluid Docs', intro: '主题使用指南', link: 'https://hexo.fluid-dev.com/docs/' }
    - { title: 'Fluid Repo', intro: '主题 GitHub 仓库', link: 'https://github.com/fluid-dev/hexo-theme-fluid' }
    - { title: 'Fluid Example', intro: '主题操作示例', link: 'https://hexo.fluid-dev.com/docs/example/' }

# 站点地图
sitemap:
  path: sitemap.xml

# 百度站点地图
baidusitemap:
  path: baidusitemap.xml