name: baiduPush

on:
  schedule:
    - cron: '0 16 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: Setup Hexo & BAIDU env
      env:
        baiduToken: ${{ secrets.baiduToken }}

      run: |
        npm install hexo-cli -g
        npm install
        sed -i "s/baiduToken/${baiduToken}/" _baiduPush.yml
    
    - name: Push to Baidu
      run: |
        hexo clean && hexo g
        npm run baidupush