name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 1

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.140.1'
        extended: true

    - name: Build
      run: hugo --minify

    - name: Login
      uses: manyuanrong/setup-ossutil@v2.0
      with:
        endpoint: ${{ secrets.ENDPOINT }}
        access-key-id: ${{ secrets.OSS_KEY_ID }}
        access-key-secret: ${{ secrets.OSS_KEY_SECRET }}

    - name: Deploy
      run: ossutil cp -rf public oss://blog-jalen/
